export interface StockInfo {
  symbol: string;
  name: string;
  exchange: "NSE" | "BSE";
  sector: string;
}

export const NSE_STOCKS: StockInfo[] = [
  { symbol: "RELIANCE.NS", name: "Reliance Industries", exchange: "NSE", sector: "Energy" },
  { symbol: "TCS.NS", name: "Tata Consultancy Services", exchange: "NSE", sector: "Technology" },
  { symbol: "HDFCBANK.NS", name: "HDFC Bank", exchange: "NSE", sector: "Financial Services" },
  { symbol: "BHARTIARTL.NS", name: "Bharti Airtel", exchange: "NSE", sector: "Communication Services" },
  { symbol: "ICICIBANK.NS", name: "ICICI Bank", exchange: "NSE", sector: "Financial Services" },
  { symbol: "INFOSYS.NS", name: "Infosys", exchange: "NSE", sector: "Technology" },
  { symbol: "SBIN.NS", name: "State Bank of India", exchange: "NSE", sector: "Financial Services" },
  { symbol: "HINDUNILVR.NS", name: "Hindustan Unilever", exchange: "NSE", sector: "Consumer Staples" },
  { symbol: "ITC.NS", name: "ITC", exchange: "NSE", sector: "Consumer Staples" },
  { symbol: "LT.NS", name: "Larsen & Toubro", exchange: "NSE", sector: "Industrials" },
  { symbol: "KOTAKBANK.NS", name: "Kotak Mahindra Bank", exchange: "NSE", sector: "Financial Services" },
  { symbol: "AXISBANK.NS", name: "Axis Bank", exchange: "NSE", sector: "Financial Services" },
  { symbol: "ASIANPAINT.NS", name: "Asian Paints", exchange: "NSE", sector: "Materials" },
  { symbol: "MARUTI.NS", name: "Maruti Suzuki India", exchange: "NSE", sector: "Consumer Discretionary" },
  { symbol: "TITAN.NS", name: "Titan Company", exchange: "NSE", sector: "Consumer Discretionary" },
  { symbol: "SUNPHARMA.NS", name: "Sun Pharmaceutical Industries", exchange: "NSE", sector: "Healthcare" },
  { symbol: "WIPRO.NS", name: "Wipro", exchange: "NSE", sector: "Technology" },
  { symbol: "ULTRACEMCO.NS", name: "UltraTech Cement", exchange: "NSE", sector: "Materials" },
  { symbol: "NESTLEIND.NS", name: "Nestle India", exchange: "NSE", sector: "Consumer Staples" },
  { symbol: "BAJFINANCE.NS", name: "Bajaj Finance", exchange: "NSE", sector: "Financial Services" },
  { symbol: "NTPC.NS", name: "NTPC", exchange: "NSE", sector: "Utilities" },
  { symbol: "M&M.NS", name: "Mahindra & Mahindra", exchange: "NSE", sector: "Consumer Discretionary" },
  { symbol: "HCLTECH.NS", name: "HCL Technologies", exchange: "NSE", sector: "Technology" },
  { symbol: "TATAMOTORS.NS", name: "Tata Motors", exchange: "NSE", sector: "Consumer Discretionary" },
  { symbol: "POWERGRID.NS", name: "Power Grid Corporation of India", exchange: "NSE", sector: "Utilities" },
  { symbol: "ADANIENT.NS", name: "Adani Enterprises", exchange: "NSE", sector: "Industrials" },
  { symbol: "ADANIPORTS.NS", name: "Adani Ports & SEZ", exchange: "NSE", sector: "Industrials" },
  { symbol: "TATASTEEL.NS", name: "Tata Steel", exchange: "NSE", sector: "Materials" },
  { symbol: "JSWSTEEL.NS", name: "JSW Steel", exchange: "NSE", sector: "Materials" },
  { symbol: "ONGC.NS", name: "Oil & Natural Gas Corporation", exchange: "NSE", sector: "Energy" },
  { symbol: "HINDALCO.NS", name: "Hindalco Industries", exchange: "NSE", sector: "Materials" },
  { symbol: "COALINDIA.NS", name: "Coal India", exchange: "NSE", sector: "Energy" },
  { symbol: "DRREDDY.NS", name: "Dr. Reddy's Laboratories", exchange: "NSE", sector: "Healthcare" },
  { symbol: "DIVISLAB.NS", name: "Divi's Laboratories", exchange: "NSE", sector: "Healthcare" },
  { symbol: "CIPLA.NS", name: "Cipla", exchange: "NSE", sector: "Healthcare" },
  { symbol: "EICHERMOT.NS", name: "Eicher Motors", exchange: "NSE", sector: "Consumer Discretionary" },
  { symbol: "BAJAJFINSV.NS", name: "Bajaj Finserv", exchange: "NSE", sector: "Financial Services" },
  { symbol: "BPCL.NS", name: "Bharat Petroleum Corporation", exchange: "NSE", sector: "Energy" },
  { symbol: "HEROMOTOCO.NS", name: "Hero MotoCorp", exchange: "NSE", sector: "Consumer Discretionary" },
  { symbol: "TATACONSUM.NS", name: "Tata Consumer Products", exchange: "NSE", sector: "Consumer Staples" },
  { symbol: "APOLLOHOSP.NS", name: "Apollo Hospitals Enterprise", exchange: "NSE", sector: "Healthcare" },
  { symbol: "SBILIFE.NS", name: "SBI Life Insurance Company", exchange: "NSE", sector: "Financial Services" },
  { symbol: "GRASIM.NS", name: "Grasim Industries", exchange: "NSE", sector: "Materials" },
  { symbol: "INDUSINDBK.NS", name: "IndusInd Bank", exchange: "NSE", sector: "Financial Services" },
  { symbol: "TECHM.NS", name: "Tech Mahindra", exchange: "NSE", sector: "Technology" },
  { symbol: "BRITANNIA.NS", name: "Britannia Industries", exchange: "NSE", sector: "Consumer Staples" },
  { symbol: "PIDILITIND.NS", name: "Pidilite Industries", exchange: "NSE", sector: "Materials" },
  { symbol: "SIEMENS.NS", name: "Siemens", exchange: "NSE", sector: "Industrials" },
  { symbol: "BOSCHLTD.NS", name: "Bosch", exchange: "NSE", sector: "Consumer Discretionary" },
  { symbol: "DABUR.NS", name: "Dabur India", exchange: "NSE", sector: "Consumer Staples" },
  { symbol: "GODREJCP.NS", name: "Godrej Consumer Products", exchange: "NSE", sector: "Consumer Staples" },
  { symbol: "ICICIGI.NS", name: "ICICI Lombard General Insurance", exchange: "NSE", sector: "Financial Services" },
  { symbol: "MCDOWELL-N.NS", name: "United Spirits", exchange: "NSE", sector: "Consumer Staples" },
  { symbol: "BANKBARODA.NS", name: "Bank of Baroda", exchange: "NSE", sector: "Financial Services" },
  { symbol: "PNB.NS", name: "Punjab National Bank", exchange: "NSE", sector: "Financial Services" },
  { symbol: "CANBK.NS", name: "Canara Bank", exchange: "NSE", sector: "Financial Services" },
  { symbol: "AMBUJACEM.NS", name: "Ambuja Cements", exchange: "NSE", sector: "Materials" },
  { symbol: "ACC.NS", name: "ACC", exchange: "NSE", sector: "Materials" },
  { symbol: "SHREECEM.NS", name: "Shree Cement", exchange: "NSE", sector: "Materials" },
  { symbol: "DLF.NS", name: "DLF", exchange: "NSE", sector: "Real Estate" },
  { symbol: "GODREJPROP.NS", name: "Godrej Properties", exchange: "NSE", sector: "Real Estate" },
  { symbol: "OBEROIRLTY.NS", name: "Oberoi Realty", exchange: "NSE", sector: "Real Estate" },
  { symbol: "HAVELLS.NS", name: "Havells India", exchange: "NSE", sector: "Consumer Discretionary" },
  { symbol: "VOLTAS.NS", name: "Voltas", exchange: "NSE", sector: "Consumer Discretionary" },
  { symbol: "CROMPTON.NS", name: "Crompton Greaves Consumer Electricals", exchange: "NSE", sector: "Consumer Discretionary" },
  { symbol: "INDIGO.NS", name: "InterGlobe Aviation (IndiGo)", exchange: "NSE", sector: "Industrials" },
  { symbol: "TRENT.NS", name: "Trent", exchange: "NSE", sector: "Consumer Discretionary" },
  { symbol: "VEDL.NS", name: "Vedanta", exchange: "NSE", sector: "Materials" },
  { symbol: "NMDC.NS", name: "NMDC", exchange: "NSE", sector: "Materials" },
  { symbol: "SAIL.NS", name: "Steel Authority of India", exchange: "NSE", sector: "Materials" },
  { symbol: "HAL.NS", name: "Hindustan Aeronautics", exchange: "NSE", sector: "Industrials" },
  { symbol: "BEL.NS", name: "Bharat Electronics", exchange: "NSE", sector: "Industrials" },
  { symbol: "ABB.NS", name: "ABB India", exchange: "NSE", sector: "Industrials" },
  { symbol: "BHEL.NS", name: "Bharat Heavy Electricals", exchange: "NSE", sector: "Industrials" },
  { symbol: "GAIL.NS", name: "Gas Authority of India", exchange: "NSE", sector: "Energy" },
  { symbol: "IOC.NS", name: "Indian Oil Corporation", exchange: "NSE", sector: "Energy" },
  { symbol: "HPCL.NS", name: "Hindustan Petroleum Corporation", exchange: "NSE", sector: "Energy" },
  { symbol: "ZOMATO.NS", name: "Zomato", exchange: "NSE", sector: "Consumer Discretionary" },
  { symbol: "NYKAA.NS", name: "FSN E-Commerce Ventures (Nykaa)", exchange: "NSE", sector: "Consumer Discretionary" },
  { symbol: "PAYTM.NS", name: "One 97 Communications (Paytm)", exchange: "NSE", sector: "Technology" },
  { symbol: "POLICYBZR.NS", name: "PB Fintech (Policybazaar)", exchange: "NSE", sector: "Financial Services" },
  { symbol: "IRCTC.NS", name: "Indian Railway Catering and Tourism", exchange: "NSE", sector: "Industrials" },
  { symbol: "HDFCLIFE.NS", name: "HDFC Life Insurance Company", exchange: "NSE", sector: "Financial Services" },
  { symbol: "MUTHOOTFIN.NS", name: "Muthoot Finance", exchange: "NSE", sector: "Financial Services" },
  { symbol: "CHOLAFIN.NS", name: "Cholamandalam Investment and Finance", exchange: "NSE", sector: "Financial Services" },
  { symbol: "LICHSGFIN.NS", name: "LIC Housing Finance", exchange: "NSE", sector: "Financial Services" },
  { symbol: "PIIND.NS", name: "PI Industries", exchange: "NSE", sector: "Materials" },
  { symbol: "UPL.NS", name: "UPL", exchange: "NSE", sector: "Materials" },
  { symbol: "COROMANDEL.NS", name: "Coromandel International", exchange: "NSE", sector: "Materials" },
  { symbol: "LALPATHLAB.NS", name: "Dr. Lal PathLabs", exchange: "NSE", sector: "Healthcare" },
  { symbol: "MAXHEALTH.NS", name: "Max Healthcare Institute", exchange: "NSE", sector: "Healthcare" },
  { symbol: "FORTIS.NS", name: "Fortis Healthcare", exchange: "NSE", sector: "Healthcare" },
  { symbol: "LUPIN.NS", name: "Lupin", exchange: "NSE", sector: "Healthcare" },
  { symbol: "AUROPHARMA.NS", name: "Aurobindo Pharma", exchange: "NSE", sector: "Healthcare" },
  { symbol: "TORNTPHARM.NS", name: "Torrent Pharmaceuticals", exchange: "NSE", sector: "Healthcare" },
  { symbol: "PERSISTENT.NS", name: "Persistent Systems", exchange: "NSE", sector: "Technology" },
  { symbol: "LTIM.NS", name: "LTIMindtree", exchange: "NSE", sector: "Technology" },
  { symbol: "MPHASIS.NS", name: "Mphasis", exchange: "NSE", sector: "Technology" },
  { symbol: "OFSS.NS", name: "Oracle Financial Services Software", exchange: "NSE", sector: "Technology" },
  { symbol: "COFORGE.NS", name: "Coforge", exchange: "NSE", sector: "Technology" },
];

export const INDEX_SYMBOLS = [
  { symbol: "^NSEI", name: "Nifty 50" },
  { symbol: "^BSESN", name: "BSE Sensex" },
  { symbol: "^NSEBANK", name: "Nifty Bank" },
  { symbol: "^CNXIT", name: "Nifty IT" },
  { symbol: "^CNXAUTO", name: "Nifty Auto" },
  { symbol: "^CNXPHARMA", name: "Nifty Pharma" },
];

export const SECTORS = [...new Set(NSE_STOCKS.map((s) => s.sector))].sort();
